BeforeAll {
    . (Join-Path -Path $PSScriptRoot -ChildPath '_InitializeTests.ps1')
    . (Join-Path -Path $PrivateFolder -ChildPath 'Add-HtmlNodeTable.ps1')
    . (Join-Path -Path $PrivateFolder -ChildPath 'Format-HtmlFontProperty.ps1')
    . (Join-Path -Path $PrivateFolder -ChildPath 'Format-HtmlTable.ps1')
    . (Join-Path -Path $PrivateFolder -ChildPath 'Format-NodeObject.ps1')
}

Describe Add-HtmlNodeTable {
    BeforeAll {
        $Images = @{
            'Main_Logo' = 'AsBuiltReport.png'
            'DomainController' = 'AD_DC.png'
            'Subnets' = 'AD_Subnets.png'
        }
        $DCsArray = @('Server-dc-01v', 'Server-dc-02v', 'Server-dc-03v', 'Server-dc-04v', 'Server-dc-05v', 'Server-dc-06v')
        $SubnetsArray = @(
            @{'IP' = '192.168.5.0' },
            @{'IP' = '192.168.7.0' },
            @{'IP' = '192.168.9.0' },
            @{'IP' = '172.16.9.0' },
            @{'IP' = '172.16.18.0' },
            @{'IP' = '10.10.8.0' }
        )


        $HTMLMultiColumn = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -AditionalInfo $SubnetsArray
        $HTMLMultiColumnDebug = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -DraftMode $true -AditionalInfo $SubnetsArray

        $HTMLMultiColumnSubGraph = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -AditionalInfo $SubnetsArray
        $HTMLMultiColumnSubGraphDebug = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -DraftMode $true -AditionalInfo $SubnetsArray

        $HTMLMultiColumnSubGraphTop = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -SubgraphLabelPos 'Top' -AditionalInfo $SubnetsArray
        $HTMLMultiColumnSubGraphDebugTop = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -MultiIcon -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -DraftMode $true -SubgraphLabelPos 'Top' -AditionalInfo $SubnetsArray



        $HTMLSingleColumn = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -Align 'Center' -iconType 'DomainController' -AditionalInfo $SubnetsArray
        $HTMLSingleColumnDebug = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -Align 'Center' -iconType 'DomainController' -DraftMode $true -AditionalInfo $SubnetsArray

        $HTMLSingleSubGraph = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -AditionalInfo $SubnetsArray
        $HTMLSingleSubGraphDebug = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -DraftMode $true -AditionalInfo $SubnetsArray

        $HTMLSingleSubGraphTop = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -SubgraphLabelPos 'Top' -AditionalInfo $SubnetsArray
        $HTMLSingleSubGraphDebugTop = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject $DCsArray -ColumnSize 3 -Align 'Center' -iconType 'DomainController' -Subgraph -SubgraphIconType 'DomainController' -SubgraphLabel 'Domain Controllers' -DraftMode $true -SubgraphLabelPos 'Top' -AditionalInfo $SubnetsArray
    }

    It 'Should return a multi column HTML table with icon image at each cell' {
        $HTMLMultiColumn | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD PORT="Icon_Server-dc-01v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-02v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-03v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-05v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-06v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a multi column HTML table with ICON text at each cell in debug mode' {
        $HTMLMultiColumnDebug | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD PORT="Icon_Server-dc-01v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-02v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-03v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-05v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-06v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a multi column HTML table with ICON text at each cell and Subgraph emulation' {
        $HTMLMultiColumnSubGraph | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD PORT="EdgeDot" ALIGN="Center" colspan="3" fixedsize="true" width="40" height="40"><IMG src="AD_DC.png"></IMG></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-01v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-02v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-03v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-05v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-06v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a multi column HTML table with ICON text at each cell and Subgraph emulation in debug mode' {
        $HTMLMultiColumnSubGraphDebug | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD PORT="EdgeDot" bgcolor="#FFCCCC" ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14"><B>AD_DC.png</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-01v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-02v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-03v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-05v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-06v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a multi column HTML table with ICON text at each cell and Subgraph emulation (Label at Top)' {
        $HTMLMultiColumnSubGraphTop | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD PORT="EdgeDot" ALIGN="Center" colspan="3" fixedsize="true" width="40" height="40"><IMG src="AD_DC.png"></IMG></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-01v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-02v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-03v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-05v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD><TD PORT="Icon_Server-dc-06v" ALIGN="Center" colspan="1"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a multi column HTML table with ICON text at each cell and Subgraph emulation in debug mode (Label at Top)' {
        $HTMLMultiColumnSubGraphDebugTop | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD PORT="EdgeDot" bgcolor="#FFCCCC" ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14"><B>AD_DC.png</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-01v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-02v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-03v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Icon_Server-dc-04v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-05v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD><TD PORT="Icon_Server-dc-06v" bgcolor="#FFCCCC" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON at top cell' {
        $HTMLSingleColumn | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD ALIGN="Center" colspan="6"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON at top cell in debug mode' {
        $HTMLSingleColumnDebug | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD bgcolor="#FFCCCC" ALIGN="Center" colspan="6"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD></TR><TR><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD></TR><TR><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD></TR><TR><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD></TR><TR><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON text at each cell and Subgraph emulation' {
        $HTMLSingleSubGraph | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD PORT="EdgeDot" ALIGN="Center" colspan="3" fixedsize="true" width="40" height="40"><IMG src="AD_DC.png"></IMG></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD ALIGN="Center" colspan="6"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON text at each cell and Subgraph emulation in debug mode' {
        $HTMLSingleSubGraphDebug | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD PORT="EdgeDot" bgcolor="#FFCCCC" ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14"><B>AD_DC.png</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD bgcolor="#FFCCCC" ALIGN="Center" colspan="6"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON text at each cell and Subgraph emulation (Label at Top)' {
        $HTMLSingleSubGraphTop | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="0" CELLBORDER="0" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="#FFFFFF"><TR><TD PORT="EdgeDot" ALIGN="Center" colspan="3" fixedsize="true" width="40" height="40"><IMG src="AD_DC.png"></IMG></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD ALIGN="Center" colspan="6"><img src="AD_DC.png"/></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD BGCOLOR="#FFFFFF" PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD BGCOLOR="#FFFFFF" PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should return a single column HTML table with ICON text at each cell and Subgraph emulation in debug mode (Label at Top)' {
        $HTMLSingleSubGraphDebugTop | Should -BeExactly '<TABLE PORT="EdgeDot" STYLE="SOLID" BORDER="1" CELLBORDER="1" CELLSPACING="5" CELLPADDING="5" BGCOLOR="#FFFFFF" COLOR="red"><TR><TD PORT="EdgeDot" bgcolor="#FFCCCC" ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14"><B>AD_DC.png</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="3"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000">Domain Controllers</FONT></TD></TR><TR><TD bgcolor="#FFCCCC" ALIGN="Center" colspan="6"><FONT FACE="Segoe Ui" Color="#000000" POINT-SIZE="14">AD_DC.png</FONT></TD></TR><TR><TD PORT="Server-dc-01v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-01v</B></FONT></TD><TD PORT="Server-dc-02v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-02v</B></FONT></TD><TD PORT="Server-dc-03v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-03v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.5.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.7.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 192.168.9.0</FONT></TD></TR><TR><TD PORT="Server-dc-04v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-04v</B></FONT></TD><TD PORT="Server-dc-05v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-05v</B></FONT></TD><TD PORT="Server-dc-06v" ALIGN="Center" colspan="1"><FONT FACE="Segoe Ui" POINT-SIZE="14" COLOR="#000000"><B>Server-dc-06v</B></FONT></TD></TR><TR><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.9.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 172.16.18.0</FONT></TD><TD ALIGN="Center" colspan="1"><FONT POINT-SIZE="14">IP: 10.10.8.0</FONT></TD></TR></TABLE>'
    }
    It 'Should include a dedicated Icon_ port on each icon TD in MultiIcon mode' {
        $HTMLMultiColumn | Should -Match 'PORT="Icon_Server-dc-01v"'
        $HTMLMultiColumn | Should -Match 'PORT="Icon_Server-dc-06v"'
    }
    It 'Should include a dedicated Icon_ port on each icon TD in MultiIcon debug mode' {
        $HTMLMultiColumnDebug | Should -Match 'PORT="Icon_Server-dc-01v"'
        $HTMLMultiColumnDebug | Should -Match 'PORT="Icon_Server-dc-06v"'
    }
    It 'Should not add an Icon_ port when MultiIcon is not used' {
        $HTMLSingleColumn | Should -Not -Match 'PORT="Icon_'
        $HTMLSingleColumnDebug | Should -Not -Match 'PORT="Icon_'
    }
    It 'Should Throw a Message' {
        { Add-HtmlNodeTable -Name 'Test' -inputObject $DCsArray -ImagesObj $Images -Align 'Center' -iconType 'DomainControlle' } | Should -Throw -ExpectedMessage 'Error: DomainControlle IconType not found in Images object'
    }
    It 'Should render array-valued multi-key AditionalInfo content when a MultiIcon group has exactly 1 item' {
        $HTMLSingleItemMultiKeyInfo = Add-HtmlNodeTable -Name 'Test' -ImagesObj $Images -inputObject @('Server-dc-01v') -iconType 'DomainController' -MultiIcon -AditionalInfo ([Ordered]@{ 'Address Space' = @('10.3.0.0/16'); 'Role' = @('Spoke') })
        $HTMLSingleItemMultiKeyInfo | Should -Match 'Address Space: 10\.3\.0\.0/16'
        $HTMLSingleItemMultiKeyInfo | Should -Match 'Role: Spoke'
        $HTMLSingleItemMultiKeyInfo | Should -Not -Match 'System\.Object\[\]'
    }
}