name: Pester Tests

on:
    push:
        branches: ["dev", "main"]
    pull_request:
        branches: ["dev"]
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
                shell: [pwsh, powershell]
                exclude:
                    - os: ubuntu-latest
                      shell: powershell
                    - os: macos-latest
                      shell: powershell
        defaults:
            run:
                shell: ${{ matrix.shell }}
        name: Pester Tests - ${{ matrix.os }} - ${{ matrix.shell }}
        steps:
            - uses: actions/checkout@v7
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: "8.0.x"
            - name: Restore dependencies Diagrammer
              run: dotnet restore ./Sources/Diagrammer
              if: matrix.shell == 'pwsh'

            - name: Restore dependencies DiaConvertImageToPDF
              run: dotnet restore ./Sources/DiaConvertImageToPDF
              if: matrix.os == 'windows-latest' && matrix.shell == 'powershell'

            - name: Build the library PWSH
              run: dotnet publish ./Sources/Diagrammer -c Release
              if: matrix.shell == 'pwsh'
            - name: Copy the library PWSH
              run:
                  Copy-Item -Path ./Sources/Diagrammer/bin/Release/net8.0/publish/*
                  -Destination ./AsBuiltReport.Diagram/Src/Bin/Assemblies/net80
                  -Recurse
              if: matrix.shell == 'pwsh'

            - name: Build the library for Windows PowerShell
              run: dotnet publish ./Sources/DiaConvertImageToPDF -c Release
              if: matrix.os == 'windows-latest' && matrix.shell == 'powershell'
            - name: Copy the library for Windows PowerShell
              run:
                  Copy-Item -Path ./Sources/DiaConvertImageToPDF/bin/Release/net48/publish/*
                  -Destination ./AsBuiltReport.Diagram/Src/Bin/Assemblies/net48
                  -Recurse
              if: matrix.os == 'windows-latest' && matrix.shell == 'powershell'

            - name: Install Graphviz
              uses: tlylt/install-graphviz@v1
              if: runner.os != 'Windows'

            - name: Run Pester Tests
              run: |
                  $CodeCoverageParam = @{}
                  $OutputFormatParam = @{ OutputFormat = 'NUnitXml' }

                  .\Tests\Invoke-Tests.ps1 @CodeCoverageParam @OutputFormatParam

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v7
              with:
                  name: test-results-${{ matrix.os }}-${{ matrix.shell }}
                  path: Tests/testResults.xml
                  retention-days: 30
